name = "acreetionos-aiden-proxy"
main = "index.js"
compatibility_date = "2026-04-26"

routes = ["acreetionos.org/api/*"]

[triggers]
# Run every 5 minutes while stabilizing. Change to "0 */6 * * *" once stable.
crons = ["*/5 * * * *"]

[vars]
DISCORD_WEBHOOK_URL = ""
ADMIN_KEY = ""
HOSTING_BUCKET = "acreetionos-hosting"
EMAIL_FROM = "developers@acreetionos.org"
VIRUSTOTAL_API_KEY = ""
