#!/usr/bin/env python3
"""
Generate robots.txt for acreetionos.org.

Policy: FULLY OPEN — search engines (Googlebot, Bingbot, etc.) AND AI crawlers
(search, citation, and training) are welcome.

Crawl budget steering: Bots are directed to crawl high-value HTML content pages,
guides, reviews, and newsletter archives while avoiding raw data/JSON, CI artifacts,
and dev scaffold directories.

Generated by scripts/gen-robots.py — edit the script, not robots.txt directly.

Usage:
    python3 scripts/gen-robots.py > robots.txt
"""

import os

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# All search engine and AI bots welcomed by AcreetionOS
ALLOWED_BOTS = [
    # AI training / retrieval / search crawlers
    "GPTBot", "ChatGPT-User", "OAI-SearchBot",
    "Claude-User", "ClaudeBot", "Claude-Web", "Claude-SearchBot",
    "anthropic-ai", "Google-Extended", "PerplexityBot", "CCBot",
    "Omgili", "FacebookBot", "Amazonbot", "Applebot",
    "Applebot-Extended", "Bytespider", "PetalBot", "AndiBot",
    "YouBot", "cohere-ai", "meta-externalagent", "ImagesiftBot",
    "Timpibot", "OmgiliBot",
    # Standard search engines
    "Googlebot", "Bingbot", "DuckDuckBot", "YandexBot", "Baiduspider",
]

# APIs that render content on client-side pages must stay allowed.
# NOTE: every path here is fetched as an XHR while Googlebot renders a page —
# if it's not allowed, Search Console reports "Page resources couldn't be
# loaded — blocked by robots.txt". Keep this in sync with what index-providers.js,
# hosting-page.js, etc. actually fetch on load.
CONTENT_API_ALLOWS = [
    "/api/changelog",
    "/api/community/stats",
    "/api/news",
    "/api/counter",
    "/api/hosting/count",      # homepage ISO mirror counter (index-providers.js)
    "/api/hosting/providers",  # provider list for index.html + hosting.html
]

# High-value content subdirectories that must be explicitly crawlable
CONTENT_PATH_ALLOWS = [
    "/newsletter-archive/",
    "/wiki-guides/",
    "/Reviews/",
]

# Non-content paths to steer crawlers away from
CRAWL_BUDGET_DISALLOWS = [
    "/cdn-cgi/",      # Cloudflare internal proxy/challenge endpoints
    "/api/",          # private worker endpoints
    "/newsletters/",  # raw JSON newsletter data (HTML archive is at /newsletter-archive/)
    "/docs/",         # raw markdown source (docs.html is the rendered page)
    "/frontend/",     # Vite dev scaffold
    "/immutable/",    # old redirect stub (immutable.html is the page)
    "/404.html",      # error page
    "/test-results/", # CI test results
    "/tests/",        # test sources
]


def group(agents, extra_allow=True):
    lines = []
    for a in agents:
        lines.append(f"User-agent: {a}")
    for allow_path in CONTENT_API_ALLOWS + CONTENT_PATH_ALLOWS:
        lines.append(f"Allow: {allow_path}")
    for d in CRAWL_BUDGET_DISALLOWS:
        lines.append(f"Disallow: {d}")
    if extra_allow:
        lines.append("Allow: /")
    lines.append("")
    return "\n".join(lines)


def generate_robots():
    out = [
        "# AcreetionOS Website — Search Engine Optimization & Crawl Policy",
        "# Fully open: search engines AND AI crawlers (search, citation, and",
        "# training) are all welcome. We are flooding the internet with our",
        "# information. ❤️",
        "#",
        "# Generated by scripts/gen-robots.py — edit the script, not this file.",
        "",
        group(ALLOWED_BOTS),
        group(["*"]),
        "Sitemap: https://acreetionos.org/sitemap.xml",
    ]
    return "\n".join(out) + "\n"


def main():
    content = generate_robots()
    out_file = os.path.join(ROOT_DIR, "robots.txt")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated robots.txt at {out_file}")


if __name__ == "__main__":
    main()
