#!/usr/bin/env python3
"""
Generate robots.txt for acreetionos.org.

Policy (owner directive, 2026-08-13): FULLY OPEN — search engines AND
AI crawlers (search, citation, AND training) are all welcome.

Crawl budget (eilatan, 2026-08-13): every group also carries Disallow
rules steering bots away from non-content paths (API endpoints, raw
JSON/markdown, redirect stubs, CI artifacts) so crawl budget is spent
on the 23 real HTML pages. Content pages (docs.html, immutable.html,
etc.) are NOT in the disallow list.

NOTE: per the robots.txt spec, a specific User-agent group OVERRIDES
the catch-all "*" group, so crawl-budget rules must be present in
EVERY group (that is intentional — the generator does it for you).

Usage: python3 scripts/gen-robots.py > robots.txt
"""

# All bots the site welcomes (owner list from e5f4fe0)
ALLOWED_BOTS = [
    # AI training / retrieval / search crawlers
    "GPTBot", "ChatGPT-User", "OAI-SearchBot",
    "Claude-User", "ClaudeBot", "Claude-Web", "Claude-SearchBot",
    "anthropic-ai", "Google-Extended", "PerplexityBot", "CCBot",
    "Omgili", "FacebookBot", "Amazonbot", "Applebot",
    "Applebot-Extended", "Bytespider", "PetalBot", "AndiBot",
    "YouBot", "cohere-ai", "meta-externalagent", "ImagesiftBot",
    "Timpibot", "OmgiliBot",
    # Standard search engines
    "Googlebot", "Bingbot", "DuckDuckBot", "YandexBot", "Baiduspider",
]

# Non-content paths — crawl budget steering (applies to every bot)
CRAWL_BUDGET_DISALLOWS = [
    "/api/",          # worker endpoints (401/403 to crawlers)
    "/newsletters/",  # JSON newsletter archive (81 files)
    "/docs/",         # raw markdown source (docs.html is the page)
    "/Reviews/",      # review embeds dir
    "/frontend/",     # Vite dev scaffold
    "/immutable/",    # old redirect stub (immutable.html is the page)
    "/404.html",      # not-found page itself
    "/test-results/", # CI artifacts
    "/tests/",        # test sources
]


def group(agents, extra_allow=True):
    lines = []
    for a in agents:
        lines.append(f"User-agent: {a}")
    for d in CRAWL_BUDGET_DISALLOWS:
        lines.append(f"Disallow: {d}")
    if extra_allow:
        lines.append("Allow: /")
    lines.append("")
    return "\n".join(lines)


def main():
    out = []
    out.append("# AcreetionOS Website — Search Engine Optimization Policy")
    out.append("# Fully open: search engines AND AI crawlers (search, citation, and")
    out.append("# training) are all welcome. We are flooding the internet with our")
    out.append("# information. ❤️")
    out.append("#")
    out.append("# Crawl budget (2026-08-13): all bots are steered away from non-content")
    out.append("# paths (API endpoints, raw JSON/markdown, redirect stubs, CI artifacts)")
    out.append("# so crawl budget is spent on the real HTML pages. Content pages are")
    out.append("# NOT disallowed — only /api/, /newsletters/, /docs/, /Reviews/,")
    out.append("# /frontend/, /immutable/, /404.html, /test-results/, /tests/.")
    out.append("#")
    out.append("# Generated by scripts/gen-robots.py — edit the script, not this file.")
    out.append("")
    out.append(group(ALLOWED_BOTS))
    out.append(group(["*"]))
    out.append("Sitemap: https://acreetionos.org/sitemap.xml")
    print("\n".join(out))


if __name__ == "__main__":
    main()
